# fly.toml app configuration file generated for infomovia on 2023-06-08T22:46:10-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "infomovia"
primary_region = "sjc"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
